version: 0.2

phases:
  build:
    commands:
      - echo Entered the buid phase
      - mvn clean package
  post_build:
    commands:
      - echo build completed successfully 

artifacts:
  files:
    - target/Spring-Demo.jar
  discard-paths: yes
